on: push
jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v3
        name: Check out code
      - name: Log in to registry
        run: |
          echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u $ --password-stdin
      - uses: mr-smithers-excellent/docker-build-push@v6
        name: Build & push Docker image

        with:
          registry: ghcr.io
          image: blocking-alpine
          tags: latest
          username: ${{ secrets.GHCR_USERNAME }}
          password: ${{ secrets.GHCR_TOKEN }}
          directory: images/blocking-alpine
